name: Job Plans

run-name: My-Jobs

on:
  workflow_dispatch:

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "A job consists of more than one step"
      - run: echo "These steps can be many or few"

  job2:
    runs-on: windows-latest
    steps:
      - run: print("Some jobs can run in parallel")
        shell: python


  job3:
    runs-on: windows-latest
    needs: 
      - job1
      - job2
    steps:
      - run: echo "Some jobs can also depend on each other"

  job4:
    runs-on: ubuntu-24.04
    needs:
      - job2
      - job3
    steps:
      - run: echo "...to form a directed acyclic graph (DAG)"
